### ISSUE TITLE
Wrong documentation on ENV

### ISSUE THREAD

**Issue by littlemove** [pantulis/tacoma#9]
The Readme states:

>Will display the export commands for the AWS_SECRET_ACCESS_KEY, AWS_ACCESS_KEY_ID credential environment variables

This is not true unless you pass the `--with-exports` to the switch command.

BTW, why show the export commands instead of show and execute by default?

**Comment by pantulis** [comment]
Fixed the README in the master branch.  Thanks!

**Comment by pantulis** [comment]
The idea was to keep Tacoma as silent as possible for using it with the command line.  The `--with-exports` options is supposed to help with scripting.
